name: Param builder Java CI

on:
  push:
    paths:
      - 'java/**'
  pull_request:
    paths:
      - 'java/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: java/ # Run the tests from the whole dir

    steps:
    - uses: actions/checkout@v4
    - name: Set up Java8
      uses: actions/setup-java@v1
      with:
          java-version: 8
    - name: Change gradlew wrapper permissions
      run: chmod +x ./gradlew
    - name: Build with Gradle
      run: ./gradlew build
